version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"

    kafka:
        image: confluentinc/cp-kafka:7.4.0
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    publisher:
        build:
            context: ./kafka-publisher
            dockerfile: Dockerfile
        container_name: publisher
        ports:
            - "8080:8080"
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - kafka

    subscriber1:
        build:
            context: ./kafka-subscriber
            dockerfile: Dockerfile
        container_name: subscriber1
        ports:
            - "8081:8081"
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        volumes:
            - ./mensajes.txt:/app/mensajes.txt
        depends_on:
            - kafka

    subscriber2:
        build:
            context: ./kafka-second-sub
            dockerfile: Dockerfile
        container_name: subscriber2
        ports:
            - "8082:8082"
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        volumes:
            - ./mensajes.txt:/app/mensajes.txt
        depends_on:
            - kafka
